services:
  - type: web
    name: aion-core
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn web_entry:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: AION_TELEGRAM_BOT
        sync: false
      - key: AION_TELEGRAM_CHAT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false